services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app